"""empty message

Revision ID: 20e466aa0bf0
Revises: 3a040f2e4147
Create Date: 2024-05-23 13:04:29.905640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e466aa0bf0'
down_revision: Union[str, None] = '3a040f2e4147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('add_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'add_at')
    # ### end Alembic commands ###
