"""empty message

Revision ID: 5dec0d22b8b8
Revises: 4dcb947d66af
Create Date: 2024-05-16 13:36:13.689682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dec0d22b8b8'
down_revision: Union[str, None] = '4dcb947d66af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('worker', 'is_fired')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('is_fired', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('worker', 'fired_at')
    # ### end Alembic commands ###
