"""empty message

Revision ID: 8e9f0f35cbcf
Revises: ffa6f326bded
Create Date: 2024-05-02 05:12:31.088818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9f0f35cbcf'
down_revision: Union[str, None] = 'ffa6f326bded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brigade', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brigade', 'rating')
    # ### end Alembic commands ###
