"""empty message

Revision ID: 9573c9ad2de7
Revises: 20b2f2b029dd
Create Date: 2024-04-26 21:47:10.926564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9573c9ad2de7'
down_revision: Union[str, None] = '20b2f2b029dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('status_type', 'is_system_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('status_type', 'is_system_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
