"""empty message

Revision ID: ca67d2afecf3
Revises: cc4cdef35ebd
Create Date: 2024-04-23 01:53:50.545450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca67d2afecf3'
down_revision: Union[str, None] = 'cc4cdef35ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brigade_xref_worker', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brigade_xref_worker', 'active')
    # ### end Alembic commands ###
