"""empty message

Revision ID: cc4cdef35ebd
Revises: 7179ed08f5b5
Create Date: 2024-04-22 18:10:09.103062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4cdef35ebd'
down_revision: Union[str, None] = '7179ed08f5b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_driver', sa.Boolean(), nullable=True))
    op.drop_column('worker', 'is_driver')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('is_driver', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('post', 'is_driver')
    # ### end Alembic commands ###
